# Generated by Django 3.2 on 2021-05-06 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_taskmodel_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='group',
            new_name='text_template',
        ),
    ]
